/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.Controller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
/**
 *
 * @author gino
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    private void clearComponents(){
        ButtonGroup.add(BtnCadCli);
        ButtonGroup.add(BtnCadAni);
        ButtonGroup.add(BtnCadEsp);
        ButtonGroup.add(BtnCadVet);
        NameInput.setText("");
        AnimalInput.setText("");
        BuscaInput.setText("");
        VeterinarioInput.setText("");
        BtnCadCli.setSelected(true);
        //controller seta tabela de cliente
        //Controller.setTableModel(MainTable, new ClienteTableModel(ClienteDAO.getInstance().retrieveAll()));
        Controller.jRadioButtonClientesSelecionado(MainTable);
        
        //controller guarda animal e cliente selecionados (vazio até agora
        Controller.setTextFields(NameInput, AnimalInput, VeterinarioInput);
        
        Controller.painelConsultasSelected(ConsultasTable);
       
        
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        AnoConsultaInput.setText(String.valueOf(currentYear));
        
        
        ConsultasTable.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            JTable table = (JTable) e.getSource();
            int row = table.rowAtPoint(e.getPoint());
            int col = table.columnAtPoint(e.getPoint());

            
            if (e.getButton() == MouseEvent.BUTTON1 && e.getClickCount() == 1) {
                
                System.out.println("Mouse pressionado na célula: " + row + ", " + col);
                Controller.updateAvailableTimes(ConsultasTable, HorarioBox);
                
            }
        }
        
        
    });
        
        SexoBox.setVisible(false);
        
        
        SexoBox.addItem("Sexo");
        SexoBox.addItem("Macho");
        SexoBox.addItem("Fêmea");
        

    }
    
    public Principal() {
        initComponents();
        clearComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MainPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        NomeTxt = new javax.swing.JLabel();
        AnimalText = new javax.swing.JLabel();
        VeterinarioText = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        AnimalInput = new javax.swing.JTextField();
        VeterinarioInput = new javax.swing.JTextField();
        ClinicaPanel = new javax.swing.JTabbedPane();
        Cadastros = new javax.swing.JPanel();
        BtnCadCli = new javax.swing.JRadioButton();
        BtnCadAni = new javax.swing.JRadioButton();
        BtnCadEsp = new javax.swing.JRadioButton();
        BtnCadVet = new javax.swing.JRadioButton();
        BtnTodos = new javax.swing.JButton();
        BtnNovo = new javax.swing.JButton();
        BuscaTxt = new javax.swing.JLabel();
        BuscaInput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainTable = new javax.swing.JTable();
        CelularTxt = new javax.swing.JLabel();
        CelularBuscaInput = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JLabel();
        EmailBuscaInput = new javax.swing.JTextField();
        SexoBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        DeleteBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        ConsultasPanel2 = new javax.swing.JPanel();
        NewConsultaBtn = new javax.swing.JButton();
        ApagaConsultaBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ConsultasTable = new javax.swing.JTable();
        VetFilter = new javax.swing.JToggleButton();
        AnimalFilter = new javax.swing.JToggleButton();
        TirarFiltros = new javax.swing.JButton();
        HorarioTxt = new javax.swing.JLabel();
        HorarioBox = new javax.swing.JComboBox<>();
        DiaConsultaInput = new javax.swing.JTextField();
        DiaTxt = new javax.swing.JLabel();
        MesTxt = new javax.swing.JLabel();
        MesConsultaInput = new javax.swing.JTextField();
        AnoTxt = new javax.swing.JLabel();
        AnoConsultaInput = new javax.swing.JTextField();
        HojeBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Header.setName(""); // NOI18N

        NomeTxt.setText("Cliente");

        AnimalText.setText("Animal");

        VeterinarioText.setText("Veterinario");

        NameInput.setEditable(false);
        NameInput.setText("Insira seu nome");
        NameInput.setVerifyInputWhenFocusTarget(false);
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        AnimalInput.setEditable(false);
        AnimalInput.setText("jTextField1");

        VeterinarioInput.setEditable(false);
        VeterinarioInput.setText("jTextField1");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AnimalText, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(VeterinarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VeterinarioInput)
                    .addComponent(AnimalInput)
                    .addComponent(NameInput))
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(NomeTxt))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnimalText)
                            .addComponent(AnimalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(VeterinarioText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(VeterinarioInput, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        ClinicaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ClinicaPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ClinicaPanelStateChanged(evt);
            }
        });
        ClinicaPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ClinicaPanelFocusGained(evt);
            }
        });
        ClinicaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClinicaPanelMousePressed(evt);
            }
        });

        BtnCadCli.setText("Cadastro Clientes");
        BtnCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadCliActionPerformed(evt);
            }
        });

        BtnCadAni.setText("Cadastro Animais");
        BtnCadAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadAniActionPerformed(evt);
            }
        });

        BtnCadEsp.setText("Cadastro Espécies");
        BtnCadEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadEspActionPerformed(evt);
            }
        });

        BtnCadVet.setText("Cadastro Veterinario");
        BtnCadVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadVetActionPerformed(evt);
            }
        });

        BtnTodos.setText("Todos");
        BtnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTodosActionPerformed(evt);
            }
        });

        BtnNovo.setText("Novo");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BuscaTxt.setText("Nome:");

        BuscaInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BuscaInput.setText("jTextField2");
        BuscaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaInputActionPerformed(evt);
            }
        });
        BuscaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscaInputKeyTyped(evt);
            }
        });

        MainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        MainTable.setMaximumSize(new java.awt.Dimension(50, 64));
        MainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MainTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(MainTable);

        CelularTxt.setText("Celular:");

        CelularBuscaInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CelularBuscaInput.setMaximumSize(new java.awt.Dimension(170, 2147483647));
        CelularBuscaInput.setVerifyInputWhenFocusTarget(false);
        CelularBuscaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelularBuscaInputActionPerformed(evt);
            }
        });
        CelularBuscaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CelularBuscaInputKeyTyped(evt);
            }
        });

        EmailTxt.setText("E-mail:");

        EmailBuscaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailBuscaInputActionPerformed(evt);
            }
        });
        EmailBuscaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailBuscaInputKeyTyped(evt);
            }
        });

        SexoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        SexoBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SexoBoxItemStateChanged(evt);
            }
        });
        SexoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoBoxActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Deletar");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastrosLayout = new javax.swing.GroupLayout(Cadastros);
        Cadastros.setLayout(CadastrosLayout);
        CadastrosLayout.setHorizontalGroup(
            CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(CadastrosLayout.createSequentialGroup()
                        .addGroup(CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastrosLayout.createSequentialGroup()
                                .addComponent(BtnCadCli)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCadAni)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCadVet)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCadEsp))
                            .addGroup(CadastrosLayout.createSequentialGroup()
                                .addComponent(BuscaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SexoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CelularTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CelularBuscaInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailBuscaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(CadastrosLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(BtnTodos)
                .addGap(18, 18, 18)
                .addComponent(BtnNovo)
                .addGap(18, 18, 18)
                .addComponent(DeleteBtn)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        CadastrosLayout.setVerticalGroup(
            CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrosLayout.createSequentialGroup()
                .addGroup(CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadCli)
                    .addComponent(BtnCadAni)
                    .addComponent(BtnCadVet)
                    .addComponent(BtnCadEsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscaTxt)
                    .addComponent(BuscaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CelularTxt)
                    .addComponent(CelularBuscaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTxt)
                    .addComponent(EmailBuscaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo)
                    .addComponent(BtnTodos)
                    .addComponent(DeleteBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ClinicaPanel.addTab("Cadastros", Cadastros);

        ConsultasPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConsultasPanel2FocusGained(evt);
            }
        });
        ConsultasPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsultasPanel2MousePressed(evt);
            }
        });

        NewConsultaBtn.setText("Novo");
        NewConsultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewConsultaBtnActionPerformed(evt);
            }
        });

        ApagaConsultaBtn.setText("Apaga");
        ApagaConsultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagaConsultaBtnActionPerformed(evt);
            }
        });

        ConsultasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ConsultasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultasTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsultasTableMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(ConsultasTable);

        VetFilter.setText("Filtrar Veterinario");
        VetFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VetFilterActionPerformed(evt);
            }
        });

        AnimalFilter.setText("Filtrar Animal");
        AnimalFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AnimalFilterItemStateChanged(evt);
            }
        });
        AnimalFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalFilterActionPerformed(evt);
            }
        });

        TirarFiltros.setText("Todos");
        TirarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TirarFiltrosActionPerformed(evt);
            }
        });

        HorarioTxt.setText("Novo Horario:");

        HorarioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        HorarioBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                HorarioBoxItemStateChanged(evt);
            }
        });

        DiaConsultaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaConsultaInputActionPerformed(evt);
            }
        });
        DiaConsultaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DiaConsultaInputKeyTyped(evt);
            }
        });

        DiaTxt.setText("Dia: ");

        MesTxt.setText("Mês: ");

        MesConsultaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesConsultaInputActionPerformed(evt);
            }
        });
        MesConsultaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MesConsultaInputKeyTyped(evt);
            }
        });

        AnoTxt.setText("Ano:");

        AnoConsultaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AnoConsultaInputKeyTyped(evt);
            }
        });

        HojeBtn.setText("Hoje");
        HojeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HojeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultasPanel2Layout = new javax.swing.GroupLayout(ConsultasPanel2);
        ConsultasPanel2.setLayout(ConsultasPanel2Layout);
        ConsultasPanel2Layout.setHorizontalGroup(
            ConsultasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultasPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(ConsultasPanel2Layout.createSequentialGroup()
                        .addComponent(TirarFiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewConsultaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ApagaConsultaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VetFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AnimalFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HojeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DiaTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DiaConsultaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MesTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MesConsultaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AnoTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AnoConsultaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HorarioTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HorarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ConsultasPanel2Layout.setVerticalGroup(
            ConsultasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultasPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TirarFiltros)
                        .addComponent(NewConsultaBtn)
                        .addComponent(ApagaConsultaBtn)
                        .addComponent(VetFilter))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AnoConsultaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HorarioTxt)
                        .addComponent(HorarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AnoTxt)
                        .addComponent(MesConsultaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MesTxt)
                        .addComponent(DiaConsultaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiaTxt)
                        .addComponent(AnimalFilter)
                        .addComponent(HojeBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        ClinicaPanel.addTab("Consultas", ConsultasPanel2);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClinicaPanel, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClinicaPanel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void ClinicaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClinicaPanelMousePressed
        
    }//GEN-LAST:event_ClinicaPanelMousePressed

    private void NewConsultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewConsultaBtnActionPerformed
         if(!Controller.createNewData(ConsultasTable)){
             JOptionPane.showMessageDialog(this, "Selecione um cliente, um animal e um veterinario");
         }
    }//GEN-LAST:event_NewConsultaBtnActionPerformed

    private void ApagaConsultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagaConsultaBtnActionPerformed
        if(!Controller.apagaConsulta(ConsultasTable)){
             JOptionPane.showMessageDialog(this, "Selecione uma consulta");
         }
    }//GEN-LAST:event_ApagaConsultaBtnActionPerformed

    private void ConsultasPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultasPanel2MousePressed
        
    }//GEN-LAST:event_ConsultasPanel2MousePressed

    private void ClinicaPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ClinicaPanelFocusGained
        
    }//GEN-LAST:event_ClinicaPanelFocusGained

    private void ConsultasPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConsultasPanel2FocusGained
        
    }//GEN-LAST:event_ConsultasPanel2FocusGained

    private void ClinicaPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ClinicaPanelStateChanged
        JTabbedPane tabbedPane = (JTabbedPane) evt.getSource();
        int selectedIndex = tabbedPane.getSelectedIndex();

        switch (selectedIndex) {
            case 0:
                break;
            case 1:
                /*if((Controller.getClienteSelecionado() == null) || (Controller.getAnimalSelecionado() == null) || (Controller.getVeterinarioSelecionado() == null)){
                    JOptionPane.showMessageDialog(this, "Selecione um cliente, um animal e um veterinario");
                    ClinicaPanel.setSelectedIndex(0);
                }
                else{
                    Controller.painelConsultasSelected(ConsultasTable);
                }*/
                break;
    }
    }//GEN-LAST:event_ClinicaPanelStateChanged

    private void ConsultasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultasTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultasTableMouseClicked

    private void ConsultasTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultasTableMousePressed
        Controller.setSelected(((GenericTableModel)ConsultasTable.getModel()).getItem(ConsultasTable.getSelectedRow()));
        
    }//GEN-LAST:event_ConsultasTableMousePressed

    private void VetFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VetFilterActionPerformed
        if(!Controller.FiltroVetSelecionado()){
            JOptionPane.showMessageDialog(this, "Selecione um veterinario");
            VetFilter.setSelected(false);
        }
        else{
            
            Controller.filtroAplicado(ConsultasTable, VetFilter, AnimalFilter, DiaConsultaInput, MesConsultaInput, AnoConsultaInput);
        }
   
    }//GEN-LAST:event_VetFilterActionPerformed

    private void AnimalFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalFilterActionPerformed
        
    }//GEN-LAST:event_AnimalFilterActionPerformed

    private void AnimalFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AnimalFilterItemStateChanged
        if(AnimalFilter.isSelected()){
            if(!Controller.FiltroAnimalSelecionado()){
            JOptionPane.showMessageDialog(this, "Selecione um animal");
            AnimalFilter.setSelected(false);
            }
            else{
                Controller.filtroAplicado(ConsultasTable, VetFilter, AnimalFilter, DiaConsultaInput, MesConsultaInput, AnoConsultaInput);
            }
        }
        else{
            Controller.filtroAplicado(ConsultasTable, VetFilter, AnimalFilter, DiaConsultaInput, MesConsultaInput, AnoConsultaInput);
        }
    }//GEN-LAST:event_AnimalFilterItemStateChanged

    private void TirarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TirarFiltrosActionPerformed
        VetFilter.setSelected(false);
        AnimalFilter.setSelected(false);
        
        DiaConsultaInput.setText("");
        MesConsultaInput.setText("");
        AnoConsultaInput.setText("");
        Controller.filtroAplicado(ConsultasTable, VetFilter, AnimalFilter, DiaConsultaInput, MesConsultaInput, AnoConsultaInput);
    }//GEN-LAST:event_TirarFiltrosActionPerformed

    private void HorarioBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_HorarioBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED && HorarioBox.getSelectedIndex() != -1) {
        System.out.println("ComboBox Pressionado");
        String selectedItem = (String) HorarioBox.getSelectedItem();
        System.out.println("Item Selecionado: " + selectedItem);
        Controller.updateHorarioConsulta(selectedItem);
        Controller.filtroAplicado(ConsultasTable, VetFilter, AnimalFilter, DiaConsultaInput, MesConsultaInput, AnoConsultaInput);
    }
    }//GEN-LAST:event_HorarioBoxItemStateChanged

    private void DiaConsultaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaConsultaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaConsultaInputActionPerformed

    private void MesConsultaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesConsultaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesConsultaInputActionPerformed

    private void DiaConsultaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DiaConsultaInputKeyTyped
            Controller.filtroAplicado(ConsultasTable, VetFilter, AnimalFilter, DiaConsultaInput, MesConsultaInput, AnoConsultaInput);
    
    }//GEN-LAST:event_DiaConsultaInputKeyTyped

    private void MesConsultaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MesConsultaInputKeyTyped
            Controller.filtroAplicado(ConsultasTable, VetFilter, AnimalFilter, DiaConsultaInput, MesConsultaInput, AnoConsultaInput);
    
    }//GEN-LAST:event_MesConsultaInputKeyTyped

    private void AnoConsultaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnoConsultaInputKeyTyped
            Controller.filtroAplicado(ConsultasTable, VetFilter, AnimalFilter, DiaConsultaInput, MesConsultaInput, AnoConsultaInput);
    
    }//GEN-LAST:event_AnoConsultaInputKeyTyped

    private void HojeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HojeBtnActionPerformed
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        int currentMonth = Calendar.getInstance().get(Calendar.MONTH);
        int currentDay = Calendar.getInstance().get(Calendar.DAY_OF_MONTH);
        
        DiaConsultaInput.setText(String.valueOf(currentDay));
        MesConsultaInput.setText(String.valueOf(currentMonth+1));
        AnoConsultaInput.setText(String.valueOf(currentYear));
    }//GEN-LAST:event_HojeBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        if(!Controller.apagaBtn(MainTable)){
            JOptionPane.showMessageDialog(this, "Selecione uma linha da coluna para poder deletar");
        }
        else{
            Controller.painelConsultasSelected(ConsultasTable);
            if(Controller.getClienteSelecionado() != null){
                NameInput.setText(Controller.getClienteSelecionado().getNome());
            }
            else{
                NameInput.setText("");
            }

            if(Controller.getAnimalSelecionado() != null){
                AnimalInput.setText(Controller.getAnimalSelecionado().getNome());
            }
            else{
                AnimalInput.setText("");
            }

            if(Controller.getVeterinarioSelecionado() != null){
                VeterinarioInput.setText(Controller.getVeterinarioSelecionado().getNome());
            }
            else{
                VeterinarioInput.setText("");
            }
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void SexoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexoBoxActionPerformed

    private void SexoBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SexoBoxItemStateChanged
        Controller.filtroAplicadoEmCadastro(MainTable, BuscaInput, CelularBuscaInput, EmailBuscaInput, SexoBox);
    }//GEN-LAST:event_SexoBoxItemStateChanged

    private void EmailBuscaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailBuscaInputKeyTyped
        Controller.filtroAplicadoEmCadastro(MainTable, BuscaInput, CelularBuscaInput, EmailBuscaInput, SexoBox);
    }//GEN-LAST:event_EmailBuscaInputKeyTyped

    private void EmailBuscaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailBuscaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailBuscaInputActionPerformed

    private void CelularBuscaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularBuscaInputKeyTyped
        Controller.filtroAplicadoEmCadastro(MainTable, BuscaInput, CelularBuscaInput, EmailBuscaInput, SexoBox);
    }//GEN-LAST:event_CelularBuscaInputKeyTyped

    private void CelularBuscaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelularBuscaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelularBuscaInputActionPerformed

    private void MainTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainTableMousePressed
        Controller.setSelected(((GenericTableModel)MainTable.getModel()).getItem(MainTable.getSelectedRow()));
    }//GEN-LAST:event_MainTableMousePressed

    private void BuscaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscaInputKeyTyped
        Controller.filtroAplicadoEmCadastro(MainTable, BuscaInput, CelularBuscaInput, EmailBuscaInput, SexoBox);
        //Controller.updateDataBySimilarName(MainTable, BuscaInput.getText());

    }//GEN-LAST:event_BuscaInputKeyTyped

    private void BuscaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaInputActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        Controller.createNewData(MainTable);

    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTodosActionPerformed
        Controller.getAllData(MainTable);
        BuscaInput.setText("");

    }//GEN-LAST:event_BtnTodosActionPerformed

    private void BtnCadVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadVetActionPerformed
        Controller.jRadioButtonVeterinarioSelecionado(MainTable);
        BuscaInput.setText("");
        CelularBuscaInput.setText("");
        EmailBuscaInput.setText("");
        SexoBox.setSelectedItem("Sexo");

        DeleteBtn.setVisible(true);

        Controller.updateHeader();
        SexoBox.setVisible(false);

        CelularTxt.setVisible(true);
        CelularBuscaInput.setVisible(true);

        EmailTxt.setVisible(true);
        EmailBuscaInput.setVisible(true);

    }//GEN-LAST:event_BtnCadVetActionPerformed

    private void BtnCadEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadEspActionPerformed
        Controller.jRadioButtonEspecieSelecionado(MainTable);

        BuscaInput.setText("");
        CelularBuscaInput.setText("");
        EmailBuscaInput.setText("");
        SexoBox.setSelectedItem("Sexo");

        DeleteBtn.setVisible(false);

        SexoBox.setVisible(false);

        CelularTxt.setVisible(false);
        CelularBuscaInput.setVisible(false);

        EmailTxt.setVisible(false);
        EmailBuscaInput.setVisible(false);

    }//GEN-LAST:event_BtnCadEspActionPerformed

    private void BtnCadAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadAniActionPerformed
        BuscaInput.setText("");
        CelularBuscaInput.setText("");
        EmailBuscaInput.setText("");
        SexoBox.setSelectedItem("Sexo");

        DeleteBtn.setVisible(true);

        Controller.updateHeader();
        if(!Controller.jRadioButtonAnimalSelecionado(MainTable)){
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
            BtnCadCli.setSelected(true);

            Controller.setTextFields(NameInput, AnimalInput, VeterinarioInput);

            BuscaInput.setText("");
            CelularBuscaInput.setText("");
            EmailBuscaInput.setText("");
            SexoBox.setSelectedItem("Sexo");

            SexoBox.setVisible(false);

            CelularTxt.setVisible(true);
            CelularBuscaInput.setVisible(true);

            EmailTxt.setVisible(true);
            EmailBuscaInput.setVisible(true);

            Controller.jRadioButtonClientesSelecionado(MainTable);
        }
        else{
            CelularTxt.setVisible(false);
            CelularBuscaInput.setVisible(false);

            EmailTxt.setVisible(false);
            EmailBuscaInput.setVisible(false);

            SexoBox.setVisible(true);
        }

    }//GEN-LAST:event_BtnCadAniActionPerformed

    private void BtnCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadCliActionPerformed
        Controller.jRadioButtonClientesSelecionado(MainTable);
        Controller.updateHeader();

        AnimalInput.setText("");

        DeleteBtn.setVisible(true);

        BuscaInput.setText("");
        CelularBuscaInput.setText("");
        EmailBuscaInput.setText("");
        SexoBox.setSelectedItem("Sexo");

        SexoBox.setVisible(false);

        CelularTxt.setVisible(true);
        CelularBuscaInput.setVisible(true);

        EmailTxt.setVisible(true);
        EmailBuscaInput.setVisible(true);
    }//GEN-LAST:event_BtnCadCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AnimalFilter;
    private javax.swing.JTextField AnimalInput;
    private javax.swing.JLabel AnimalText;
    private javax.swing.JTextField AnoConsultaInput;
    private javax.swing.JLabel AnoTxt;
    private javax.swing.JButton ApagaConsultaBtn;
    private javax.swing.JRadioButton BtnCadAni;
    private javax.swing.JRadioButton BtnCadCli;
    private javax.swing.JRadioButton BtnCadEsp;
    private javax.swing.JRadioButton BtnCadVet;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnTodos;
    private javax.swing.JTextField BuscaInput;
    private javax.swing.JLabel BuscaTxt;
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JPanel Cadastros;
    private javax.swing.JTextField CelularBuscaInput;
    private javax.swing.JLabel CelularTxt;
    private javax.swing.JTabbedPane ClinicaPanel;
    private javax.swing.JPanel ConsultasPanel2;
    private javax.swing.JTable ConsultasTable;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField DiaConsultaInput;
    private javax.swing.JLabel DiaTxt;
    private javax.swing.JTextField EmailBuscaInput;
    private javax.swing.JLabel EmailTxt;
    private javax.swing.JPanel Header;
    private javax.swing.JButton HojeBtn;
    private javax.swing.JComboBox<String> HorarioBox;
    private javax.swing.JLabel HorarioTxt;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTable MainTable;
    private javax.swing.JTextField MesConsultaInput;
    private javax.swing.JLabel MesTxt;
    private javax.swing.JTextField NameInput;
    private javax.swing.JButton NewConsultaBtn;
    private javax.swing.JLabel NomeTxt;
    private javax.swing.JComboBox<String> SexoBox;
    private javax.swing.JButton TirarFiltros;
    private javax.swing.JToggleButton VetFilter;
    private javax.swing.JTextField VeterinarioInput;
    private javax.swing.JLabel VeterinarioText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
