/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.Controller;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author gino
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    private void clearComponents(){
        NameInput.setText("");
        ButtonGroup.add(BtnCadCli);
        ButtonGroup.add(BtnCadAni);
        ButtonGroup.add(BtnCadEsp);
        ButtonGroup.add(BtnCadVet);
        NameInput.setText("");
        AnimalInput.setText("");
        BuscaInput.setText("");
        BtnCadCli.setSelected(true);
        //controller seta tabela de cliente
        //Controller.setTableModel(MainTable, new ClienteTableModel(ClienteDAO.getInstance().retrieveAll()));
        Controller.jRadioButtonClientesSelecionado(MainTable);
        
        //controller guarda animal e cliente selecionados (vazio até agora
        Controller.setTextFields(NameInput, AnimalInput);
    }
    
    public Principal() {
        initComponents();
        clearComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        NomeTxt = new javax.swing.JLabel();
        AnimalText = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        AnimalInput = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Cadastros = new javax.swing.JPanel();
        BtnCadCli = new javax.swing.JRadioButton();
        BtnCadAni = new javax.swing.JRadioButton();
        BtnCadEsp = new javax.swing.JRadioButton();
        BtnCadVet = new javax.swing.JRadioButton();
        BtnTodos = new javax.swing.JButton();
        BtnNovo = new javax.swing.JButton();
        BtnApaga = new javax.swing.JButton();
        BuscaTxt = new javax.swing.JLabel();
        BuscaInput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setName(""); // NOI18N

        NomeTxt.setText("Cliente");

        AnimalText.setText("Animal");

        NameInput.setEditable(false);
        NameInput.setText("Insira seu nome");
        NameInput.setVerifyInputWhenFocusTarget(false);
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        AnimalInput.setEditable(false);
        AnimalInput.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnimalText, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                    .addComponent(AnimalInput))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NomeTxt)
                        .addGap(18, 18, 18)
                        .addComponent(AnimalText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AnimalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnCadCli.setText("Cadastro Clientes");
        BtnCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadCliActionPerformed(evt);
            }
        });

        BtnCadAni.setText("Cadastro Animais");
        BtnCadAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadAniActionPerformed(evt);
            }
        });

        BtnCadEsp.setText("Cadastro Espécies");
        BtnCadEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadEspActionPerformed(evt);
            }
        });

        BtnCadVet.setText("Cadastro Veterinario");
        BtnCadVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadVetActionPerformed(evt);
            }
        });

        BtnTodos.setText("Todos");
        BtnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTodosActionPerformed(evt);
            }
        });

        BtnNovo.setText("Novo");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnApaga.setText("Apaga");

        BuscaTxt.setText("Busca");

        BuscaInput.setText("jTextField2");
        BuscaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaInputActionPerformed(evt);
            }
        });
        BuscaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscaInputKeyTyped(evt);
            }
        });

        MainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        MainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MainTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(MainTable);

        javax.swing.GroupLayout CadastrosLayout = new javax.swing.GroupLayout(Cadastros);
        Cadastros.setLayout(CadastrosLayout);
        CadastrosLayout.setHorizontalGroup(
            CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrosLayout.createSequentialGroup()
                .addGroup(CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrosLayout.createSequentialGroup()
                        .addComponent(BtnCadCli)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCadAni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCadEsp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCadVet))
                    .addGroup(CadastrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnTodos)
                        .addGap(12, 12, 12)
                        .addComponent(BtnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(BtnApaga)
                        .addGap(44, 44, 44)
                        .addComponent(BuscaTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 278, Short.MAX_VALUE))
            .addGroup(CadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        CadastrosLayout.setVerticalGroup(
            CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrosLayout.createSequentialGroup()
                .addGroup(CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadCli)
                    .addComponent(BtnCadAni)
                    .addComponent(BtnCadEsp)
                    .addComponent(BtnCadVet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTodos)
                    .addComponent(BtnNovo)
                    .addComponent(BtnApaga)
                    .addComponent(BuscaTxt)
                    .addComponent(BuscaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Cadastros", Cadastros);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane2)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void BtnCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadCliActionPerformed
        Controller.jRadioButtonClientesSelecionado(MainTable);
        //Controller.setTableModel(MainTable, new ClientTableModel(ClienteDAO.getInstance().retrieveAll()));
    }//GEN-LAST:event_BtnCadCliActionPerformed

    private void BtnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTodosActionPerformed
       
    }//GEN-LAST:event_BtnTodosActionPerformed

    private void BtnCadAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadAniActionPerformed
        if(!Controller.jRadioButtonAnimalSelecionado(MainTable)){
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
        }
        /*
        if(Controller.getClienteSelecionado() != null){
            Controller.setTableModel(MainTable, new AnimalTableModel(AnimalDAO.getInstance().retrieveAll()));
        }
        else{
            Controller.setTableModel(MainTable, new AnimalTableModel(new ArrayList()));
            JOptionPane.showMessageDialog(this, "Selecione um cliente.");
        
        */
    }//GEN-LAST:event_BtnCadAniActionPerformed

    private void MainTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainTableMousePressed
        Controller.setSelected(((GenericTableModel)MainTable.getModel()).getItem(MainTable.getSelectedRow()));
    }//GEN-LAST:event_MainTableMousePressed

    private void BtnCadEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadEspActionPerformed
        Controller.jRadioButtonEspecieSelecionado(MainTable);
    }//GEN-LAST:event_BtnCadEspActionPerformed

    private void BtnCadVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadVetActionPerformed
        Controller.jRadioButtonVeterinarioSelecionado(MainTable);
    }//GEN-LAST:event_BtnCadVetActionPerformed

    private void BuscaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaInputActionPerformed

    private void BuscaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscaInputKeyTyped
        
        Controller.updateDataBySimilarName(MainTable, BuscaInput.getText());
        /*if(MainTable.getModel() instanceof ClienteTableModel){
            ((GenericTableModel)MainTable.getModel()).addListOfItems(Controller.getClientsBySimilarName(BuscaInput.getText()));
        }*/
    }//GEN-LAST:event_BuscaInputKeyTyped

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        if(MainTable.getModel() instanceof ClienteTableModel){
            ((GenericTableModel)MainTable.getModel()).addItem(Controller.adicionaCliente("", "", "", "", ""));
        }
        
    }//GEN-LAST:event_BtnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnimalInput;
    private javax.swing.JLabel AnimalText;
    private javax.swing.JButton BtnApaga;
    private javax.swing.JRadioButton BtnCadAni;
    private javax.swing.JRadioButton BtnCadCli;
    private javax.swing.JRadioButton BtnCadEsp;
    private javax.swing.JRadioButton BtnCadVet;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnTodos;
    private javax.swing.JTextField BuscaInput;
    private javax.swing.JLabel BuscaTxt;
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JPanel Cadastros;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTable MainTable;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel NomeTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
